version: '3'

services:
  game-api:
    build:
      dockerfile: dockerfile.dev
      context: .
    restart: always
    volumes:
      - '.:/app'
    ports:
      - '5004:5004'
  game-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./dev_db/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
